# MD012 - Multiple consecutive blank lines
MD012:
  maximum: 2

# MD013 - Line length
MD013:
  line_length: 100


# MD024/no-duplicate-heading/no-duplicate-header - Multiple headings with the same content
MD024:
  # Only check sibling headings
  siblings_only: true
