ci:
  autoupdate_schedule: weekly
  autoupdate_commit_msg: 'ci(pre-commit): pre-commit.ci autoupdate'
  autofix_commit_msg: 'ci(pre-commit): pre-commit.ci autofixes'


repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.40.0
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages:
          - post-commit
          - push

  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black

  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.1
    hooks:
      - id: absolufy-imports
        files: emotional\/.+\.py
        args: [--never]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.237
    hooks:
      - id: ruff

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
